basePath: /
definitions:
  models.Cashback:
    properties:
      cashback_amount:
        example: 100.5
        type: number
      cinerama_user_id:
        example: 456
        type: integer
      created_at:
        example: "2024-03-20T10:00:00Z"
        type: string
      deleted_at:
        example: "null"
        type: string
      id:
        example: 1
        type: integer
      turon_user_id:
        example: 123
        type: integer
      updated_at:
        example: "2024-03-20T10:00:00Z"
        type: string
    type: object
  models.CashbackRequest:
    properties:
      cashback_amount:
        type: number
      cinerama_user_id:
        type: integer
      host_ip:
        type: string
      turon_user_id:
        type: integer
      type:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: CASHBACK SERVICE API
  title: Cashback Service API
  version: "1.0"
paths:
  /cashback/{turon_user_id}:
    get:
      consumes:
      - application/json
      description: Cashback amount of the user
      parameters:
      - description: Turon User ID
        in: path
        name: turon_user_id
        required: true
        type: integer
      - description: Start date
        example: "2024-03-01"
        format: date
        in: query
        name: from_date
        type: string
      - description: End date
        example: "2024-03-20"
        format: date
        in: query
        name: to_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cashback'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: GET Cashback
      tags:
      - cashback
  /cashback/{turon_user_id}/history:
    get:
      consumes:
      - application/json
      description: Get cashback history with optional date filtering and pagination
      parameters:
      - description: Turon User ID
        in: path
        name: turon_user_id
        required: true
        type: integer
      - description: Start date
        example: "2024-03-01"
        format: date
        in: query
        name: from_date
        type: string
      - description: End date
        example: "2024-03-20"
        format: date
        in: query
        name: to_date
        type: string
      - default: 1
        description: Page number
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        maximum: 100
        minimum: 1
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 'data: array of cashback history, pagination: pagination info'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: CashbackHistory of the user
      tags:
      - cashback
  /cashback/decrease:
    post:
      consumes:
      - application/json
      description: Cashback amount decrease of the user
      parameters:
      - description: 'Cashback amount decrease '
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CashbackRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cashback amount decrease
      tags:
      - cashback
  /cashback/increase:
    post:
      consumes:
      - application/json
      description: Increase cashback of the user
      parameters:
      - description: Cashback increase
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CashbackRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cashback increase
      tags:
      - cashback
swagger: "2.0"
